# static.yml örneği

site_name: "My Static Website"
site_url: "https://www.mystaticsite.com"
site_description: "Bu, basit bir statik site örneğidir."

# Genel site ayarları
theme: "minimal"  # Temanızı buraya yazabilirsiniz.
base_url: "/"

# Sayfalar
pages:
  - title: "Ana Sayfa"
    url: "/"
    template: "index.html"

  - title: "Hakkımızda"
    url: "/about"
    template: "about.html"

  - title: "İletişim"
    url: "/contact"
    template: "contact.html"

# Sosyal medya bağlantıları
social:
  twitter: "https://twitter.com/mystaticsite"
  facebook: "https://facebook.com/mystaticsite"
  linkedin: "https://linkedin.com/company/mystaticsite"

# Dil ayarları
language: "tr"

# SEO ayarları
seo:
  meta_description: "Bu, My Static Website hakkında kısa bir açıklamadır."
  meta_keywords: "statik, web, site, örnek"
  google_analytics: "UA-XXXXXXX-X"  # Google Analytics kimliğinizi buraya ekleyin
