<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sdwird - Welcome</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Welcome to sdwird</h1>
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section id="home">
            <h2>Home</h2>
            <p>This is the homepage of sdwird, your go-to site for amazing content!</p>
        </section>

        <section id="about">
            <h2>About</h2>
            <p>sdwird is a platform created to showcase modern web development techniques and content delivery.</p>
        </section>

        <section id="contact">
            <h2>Contact</h2>
            <p>If you'd like to get in touch, email us at <a href="mailto:contact@sdwird.com">contact@sdwird.com</a>.</p>
        </section>
    </main>

    <footer>
        <p>&copy; 2024 sdwird. All rights reserved.</p>
    </footer>
</body>
</html>
